apiVersion: v1
kind: Service
metadata:
  name: {{ include "softhsm.fullname" . }}
  labels:
    {{- include "softhsm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: tcp
  selector:
    {{- include "softhsm.selectorLabels" . | nindent 4 }}
